{% set name = "poetry" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/poetry-{{ version }}.tar.gz
  sha256: 27676b30e17c44b836cc002bf3cf8472f01fce886bddb4987caf14aeb4663165

build:
  noarch: python
  number: 0
  # You NEED to include the platform in the build string to avoid hash collisions
  string: linux_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [linux]
  string: osx_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [osx]
  string: win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [win]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - poetry = poetry.console.application:main

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.5.0
    - pip
  run:
    # Update version number in URL before checking dependencies
    # https://github.com/python-poetry/poetry/blob/1.7.1/pyproject.toml
    - cachecontrol >=0.14.0,<0.15.0
    - python >=3.8,<4.0
    - poetry-core 1.9.0
    - poetry-plugin-export >=1.6.0,<2.0.0
    - python-build >=1.0.3,<2.0.0
    - cachecontrol-with-filecache >=0.14.0,<0.15.0
    - cleo >=2.1.0,<3.0.0
    - crashtest >=0.4.1,<0.5.0
    - dulwich >=0.21.2,<0.22.0
    - python-fastjsonschema >=2.18.0,<3.0.0
    # for all python to stay noarch: python
    - importlib-metadata >=4.4
    - python-installer >=0.7.0,<0.8.0
    - keyring >=24.0.0,<25.0.0
    - packaging >=20.5
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.9.4,<2.0.0
    - platformdirs >=3.0.0,<5
    - pyproject_hooks >=1.0.0,<2.0.0
    - requests >=2.26.0,<3.0.0
    - requests-toolbelt >=1.0.0,<2.0.0
    - shellingham >=1.5.0,<2.0.0
    # for all python to stay noarch: python
    - tomli >=2.0.1,<3.0.0
    - tomlkit >=0.11.4,<1.0.0
    - trove-classifiers >=2022.5.19
    - virtualenv >=20.23.0,<21.0.0
    - xattr >=1.0.0,<2.0.0    # [osx]

    # Keep the package noarch
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]

test:
  requires:
    - pip
  commands:
    - pip check
    - poetry -V
  imports:
    - poetry
    - poetry.config

about:
  home: https://python-poetry.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy
  dev_url: https://github.com/python-poetry/poetry
  doc_url: https://python-poetry.org/docs/

extra:
  recipe-maintainers:
    - BastianZim
    - ocefpaf
    - maresb
    - xylar
