{% set version = "1.2.0a2" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: 4bad54dd1b40fd7b7efe90f05288ebab3d55b091cb682c847eac1d24ff1d1e31

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - poetry = poetry.console.application:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - poetry-core >=1.1.0a6,<2.0.0
  run:
    # https://github.com/python-poetry/poetry/blob/{{ version }}/pyproject.toml
    - python
    - poetry-core >=1.1.0a6,<2.0.0
    - cleo >=1.0.0a4,<2.0.0
    - crashtest >=0.3.0,<0.4.0
    - requests >=2.18,<3.0
    - cachy >=0.3.0,<0.4.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - cachecontrol >=0.12.4,<0.13.0

    # cachecontrol:filecache  <https://github.com/ionrock/v{{ cachecontrol_version }}/blob/master/setup.py>
    - lockfile >=0.9

    - pkginfo >=1.5,<2.0
    - html5lib >=1.0,<2.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.7.0,<1.0.0
    - pexpect >=4.7.0,<5.0.0
    - packaging >=20.4,<21.0
    - virtualenv >=20.4.3,<20.4.5
    - keyring >=21.2.0
    - entrypoints >=0.3,<0.4
    - importlib-metadata >=1.6.0,<2.0.0  # [py<38]
    # - dataclasses  # [py<=36]  # Not needed since we only target py>=3.7

test:
  requires:
    - pip
  commands:
    - pip check
    - poetry -V
  imports:
    - poetry
    - poetry.config

about:
  home: https://python-poetry.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy
  dev_url: https://github.com/python-poetry/poetry
  doc_url: https://python-poetry.org/docs/

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
    - xylar
