{% set version = "1.0.9" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: 0a4c56983546964b47cbbe0e1b49fef5662277bbf0673e3e350e1215560377ab

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - poetry = poetry.console:main

requirements:
  host:
    - python
    - pip
    - intreehooks
    - cachecontrol >=0.12.4,<0.13.0
    # cachecontrol:filecache
    - lockfile >=0.9
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.2,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.11,<0.6.0
    # legacy python
    - importlib_metadata >=1.1.3,<1.2.0  # [py<38]
    # modern python
    - keyring >=18.0.1,<19.0.0  # [py>=35]
  run:
    - python
    - cachecontrol >=0.12.4,<0.13.0
    # cachecontrol:filecache
    - lockfile >=0.9
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.2,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.11,<0.6.0
    # legacy python
    - importlib_metadata >=1.1.3,<1.2.0  # [py<38]
    # modern python
    - keyring >=18.0.1,<19.0.0  # [py>=35]

test:
  requires:
    - pip
  commands:
    - poetry -V
    - pip check
  imports:
    - poetry

about:
  home: https://poetry.eustace.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy

extra:
  recipe-maintainers:
    - ocefpaf
