{% set version = "1.0.4" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: f7057fe9549d45ecff784cbc2b3f303e5f2f05c241cc74c0acc5820576cf9216

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - poetry = poetry.console:main

requirements:
  host:
    - python
    - pip
    - intreehooks
    - cachecontrol >=0.12.4,<0.13.0
    - lockfile >=0.9  # cachecontrol:filecache
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.1,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.8,<0.6.0
    # legacy python
    - typing >=3.6,<4  # [py<35]
    - pathlib2 >=2.3,<3  # [py<35]
    - glob2 >=0.6,<1  # [py<35]
    - keyring >=18.0,<19  # [py<35]
    - virtualenv >=16.0,<17  # [py27]
    - functools32 >=3.2.3,<3.3  # [py27]
    - subprocess32 >=3.5,<4  # [py<35]
    - importlib_metadata >=0.23,<1  # [py<38]
    # modern python
    - keyring >=19.0,<20  # [py>=35]
  run:
    - python
    - cachecontrol >=0.12.4,<0.13.0
    - lockfile >=0.9  # cachecontrol:filecache
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.1,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.8,<0.6.0
    # legacy python
    - typing >=3.6,<4  # [py<35]
    - pathlib2 >=2.3,<3  # [py<35]
    - glob2 >=0.6,<1  # [py<35]
    - keyring >=18.0,<19  # [py<35]
    - virtualenv >=16.0,<17  # [py27]
    - functools32 >=3.2.3,<3.3  # [py27]
    - subprocess32 >=3.5,<4  # [py<35]
    - importlib_metadata >=0.23,<1  # [py<38]
    # modern python
    - keyring >=19.0,<20  # [py>=35]

test:
  imports:
    - poetry
    - poetry.console
    - poetry.console.commands
    - poetry.console.commands.cache
    - poetry.console.commands.debug
    - poetry.console.commands.self
    - poetry.installation
    - poetry.io
    - poetry.json
    - poetry.layouts
    - poetry.masonry
    - poetry.masonry.builders
    - poetry.masonry.publishing
    - poetry.masonry.utils
    - poetry.mixology
    - poetry.packages
    - poetry.packages.constraints
    - poetry.packages.utils
    - poetry.puzzle
    - poetry.puzzle.operations
    - poetry.repositories
    - poetry.semver
    - poetry.spdx
    - poetry.utils
    - poetry.vcs
    - poetry.version
  commands:
    - poetry --help

about:
  home: https://poetry.eustace.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy

extra:
  recipe-maintainers:
    - ocefpaf
