{% set version = "1.0.5" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: 8e195ea8a4bce4f418a23fd828aa2f9ce06be7655720efd1d95beb0ee641030a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - poetry = poetry.console:main

requirements:
  host:
    - python
    - pip
    - intreehooks
    - cachecontrol >=0.12.4,<0.13.0
    # cachecontrol:filecache
    - lockfile >=0.9
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.2,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.11,<0.6.0
    # legacy python
    - importlib_metadata >=1.1.3,<1.2.0  # [py<38]
    - virtualenv >=16.7.9,<17.0.0  # [py27]
    - functools32 >=3.2.3,<4.0.0  # [py27]
    - typing >=3.6,<4  # [py<35]
    - pathlib2 >=2.3,<3.0  # [py<35]
    - glob2 >=0.6,<0.7  # [py<35]
    - keyring >=18.0.1,<19  # [py<35]
    - subprocess32 >=3.5,<4  # [py<35]
    # modern python
    - keyring >=18.0.1,<19.0.0  # [py>=35]
  run:
    - python
    - cachecontrol >=0.12.4,<0.13.0
    # cachecontrol:filecache
    - lockfile >=0.9
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.7.6,<0.8.0
    - clikit >=0.4.2,<0.5.0
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.8.0,<0.9.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.5.11,<0.6.0
    # legacy python
    - importlib_metadata >=1.1.3,<1.2.0  # [py<38]
    - virtualenv >=16.7.9,<17.0.0  # [py27]
    - functools32 >=3.2.3,<4.0.0  # [py27]
    - typing >=3.6,<4  # [py<35]
    - pathlib2 >=2.3,<3.0  # [py<35]
    - glob2 >=0.6,<0.7  # [py<35]
    - keyring >=18.0.1,<19  # [py<35]
    - subprocess32 >=3.5,<4  # [py<35]
    # modern python
    - keyring >=18.0.1,<19.0.0  # [py>=35]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - poetry
  commands:
    - poetry -V

about:
  home: https://poetry.eustace.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy

extra:
  recipe-maintainers:
    - ocefpaf
