{% set version = "1.1.9" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: 481c6264cecf907c47e82216205e7f8486d70e4d54c721b8c3fc651364b0d0ca

build:
  number: 0
  skip: true  # [py<35]
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - poetry = poetry.console:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - poetry-core >=1.0.0,<2.0.0
  run:
    - python
    - cachecontrol >=0.12.4,<0.13.0
    # cachecontrol:filecache
    - lockfile >=0.9
    - cachy >=0.3.0,<0.4.0
    - cleo >=0.8.1,<0.9.0
    - clikit >=0.6.2,<0.7.0
    - crashtest >=0.3.0,<0.4.0  # [py>=36]
    - html5lib >=1.0,<2.0
    - jsonschema >=3.1,<4.0
    - pexpect >=4.7.0,<5.0.0
    - pkginfo >=1.4,<2.0
    - pyparsing >=2.2,<3.0
    - pyrsistent >=0.14.2,<0.15.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - requests >=2.18,<3.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.7.0,<1.0.0
    - packaging >=20.4,<21.0
    - poetry-core >=1.0.4,<1.1.0
    - virtualenv >=20.0.26,<21.0.0
    - keyring >=21.2.0,<21.3.0  # [py>=36]
    # legacy python
    - importlib-metadata >=1.6.0,<2.0.0  # [py<38]

test:
  requires:
    - pip
  commands:
    - pip check
    - poetry -V
  imports:
    - poetry
    - poetry.config

about:
  home: https://poetry.eustace.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy

extra:
  recipe-maintainers:
    - ocefpaf
