{% set version = "1.2.0" %}

package:
  name: poetry
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/poetry/poetry-{{ version }}.tar.gz
  sha256: 17c527d5d5505a5a7c5c14348d87f077d643cf1f186321530cde68e530bba59f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - poetry = poetry.console:main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - poetry-core >=1.0.7,<1.1.0
  run:
    # Update version number in URL before checking dependencies
    # https://github.com/python-poetry/poetry/blob/1.1.12/pyproject.toml
    - python
    - poetry-core >=1.0.7,<1.1.0
    - cleo >=0.8.1,<0.9.0
    - clikit >=0.6.2,<0.7.0
    - crashtest >=0.3.0,<0.4.0
    - requests >=2.18,<3.0
    - cachy >=0.3.0,<0.4.0
    - requests-toolbelt >=0.9.1,<0.10.0
    - cachecontrol >=0.12.9,<0.13.0

    # cachecontrol:filecache  <https://github.com/ionrock/cachecontrol/blob/master/setup.py>
    - lockfile >=0.9

    - pkginfo >=1.4,<2.0
    - html5lib >=1.0,<2.0
    - shellingham >=1.1,<2.0
    - tomlkit >=0.7.0,<1.0.0
    - pexpect >=4.7.0,<5.0.0
    - packaging >=20.4,<21.0
    - virtualenv >=20.0.26,<21.0.0
    - keyring >=21.2.0
    - importlib-metadata >=1.6.0,<2.0.0  # [py<38]

    # Workaround for <https://github.com/conda-forge/pexpect-feedstock/issues/26>
    - ptyprocess >=0.5

test:
  requires:
    - pip
  commands:
    - pip check
    - poetry -V
  imports:
    - poetry
    - poetry.config

about:
  home: https://python-poetry.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy
  dev_url: https://github.com/python-poetry/poetry
  doc_url: https://python-poetry.org/docs/

extra:
  recipe-maintainers:
    - ocefpaf
    - maresb
    - xylar
