schema_version: 1

context:
  name: poetry
  version: 2.3.1

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/poetry-${{ version }}.tar.gz
  sha256: 423cbccfe3533155ce9f49e929780a1386e564b2d97d2380664ea388cfe1191c

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - poetry = poetry.console.application:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core >=2.0
    - pip
  run:
    # Update version number in URL before checking dependencies
    # https://github.com/python-poetry/poetry/blob/2.0.0/pyproject.toml
    - python >=${{ python_min }},<4.0
    - poetry-core ==2.3.0
    - python-build >=1.2.1,<2.0.0
    # the following syntax makes the update-grayskull bot happier
    - cachecontrol >=0.14.0,<0.15.0
    - cachecontrol-with-filecache
    - cleo >=2.1.0,<3.0.0
    - dulwich >=0.25.0,<0.26.0
    - python-fastjsonschema >=2.18.0,<3.0.0
    - python-installer >=0.7.0,<0.8.0
    - keyring >=25.1.0,<26.0.0
    - packaging >=24.2
    - pkginfo >=1.12,<2.0
    - platformdirs >=3.0.0,<5
    - pyproject_hooks >=1.0.0,<2.0.0
    - requests >=2.26,<3.0
    - requests-toolbelt >=1.0.0,<2.0.0
    - shellingham >=1.5,<2.0
    # for all python to stay noarch: python
    - tomli >=2.0.1,<3.0.0
    - tomlkit >=0.11.4,<1.0.0
    - trove-classifiers >=2022.5.19
    - virtualenv >=20.26.6
    - if: osx
      then: xattr >=1.0.0,<2.0.0
    - findpython >=0.6.2,<0.8.0
    - pbs-installer >=2025.6.10
    # pbs-installer[download]
    - httpx <1,>=0.27.0
    # pbs-installer[install]
    - zstandard >=0.21.0
    # Keep the package noarch
    - if: linux
      then: __linux
    - if: osx
      then: __osx
    - if: win
      then: __win

tests:
  - python:
      imports:
        - poetry
        - poetry.config
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - poetry -V

about:
  license: MIT
  license_file: LICENSE
  summary: Python dependency management and packaging made easy
  homepage: https://python-poetry.org/
  repository: https://github.com/python-poetry/poetry
  documentation: https://python-poetry.org/docs/

extra:
  recipe-maintainers:
    - BastianZim
    - ocefpaf
    - maresb
    - xylar
