appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: azure}
travis:
  secure: {BINSTAR_TOKEN: kmeaAuegFGCwtuYIdTe5OFOR+UFOznQZW6QPfBOYfOy6Fzy7x382hJbFnUFwFns0nn3IxuwzcS8J9d6qt8ZgtRAxjhqh1YE9S2zHAWeMI7nuOyE2G+qQE8W9vLBcD+1TJ3vc1rD4pWm8vG2qZY5/YuTMaMby/i35QOwsKc63VhNKomhIApXb4Y7xZyC/wE7wAGoCnksxXy5woF023A87F9T4jlVP49AMKWPwTmblF51oBg3hPA3ud0KfpVVAGC2E2e3deaGbebo6AEDOcMaT112F5fIvEEpIq29R+VLOxhRQqg3RvmPpx00o66k8NgW8/SfWLg6LxUKigj7t6x1aLmJ2JhdBK2CCMBq9qtO74s3fQqI72MR3TlxvSbJ+T8FXW7b7TUCixlYT4W2wLzrh22adrzIr732Un9qMEFbonsKCd8l2CueoLCV+0sOydjOQnLVGHKZ+noLY9EL5yeWvbFzdOx/+bmzj3G5qnXnebPJmRrSPnmuImRb1PpcJ0i9h7ZLrWa16d4Vgj19MUHKdyKdJzU2MD8fwUUh/9VDWJOEHYfLhD4Rqj24uvKxstx82q8Eks4seqNZOlAsIyV+v9p3xqMwZeTAGt0QayX2kAgEDuH5L6+6aOIYUG+QJRA87ajBSzkUYgJMhutaeNjNJA2jGtEGebUBcfvWuolxwLS0=}
