bot:
  inspection: update-grayskull
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
noarch_platforms:
- linux_64
- osx_64
- win_64
